# Generated by Django 6.1.1 on 2026-09-08 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('title',)},
        ),
    ]
