# Generated by Django 6.1.1 on 2026-09-08 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0002_alter_category_options_alter_room_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='points',
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('task_type', models.CharField(choices=[('info', 'Information'), ('answer', 'Answer'), ('flag', 'Flag')], default='answer', max_length=10)),
                ('answer', models.CharField(blank=True, max_length=255)),
                ('points', models.PositiveIntegerField(default=10)),
                ('order', models.PositiveIntegerField(default=1)),
                ('hint', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='rooms.room')),
            ],
            options={
                'ordering': ('order',),
            },
        ),
    ]
