# Generated by Django 6.1.1 on 2026-09-08 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_remove_room_points_task'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('name',), 'verbose_name_plural': 'Categories'},
        ),
    ]
